// <auto-generated />
namespace RIPASTOP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newContractEventCols : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newContractEventCols));
        
        string IMigrationMetadata.Id
        {
            get { return "202005282135543_newContractEventCols"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
