//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIPASTOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cities
    {
        public string State { get; set; }
        public string City { get; set; }
        public string City_Inactive_Date { get; set; }
        public string City_AddTime { get; set; }
    }
}
