//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIPASTOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CJISOffenseCodes
    {
        public string Offense_Validation_CD { get; set; }
        public int Offense_Code { get; set; }
        public string Offense_Txn_Type_CD { get; set; }
        public string Offense_Statute { get; set; }
        public string Offense_Type_of_Statute_CD { get; set; }
        public string Statute_Literal_25 { get; set; }
        public string Offense_Default_Type_of_Charge { get; set; }
        public string Offense_Type_of_Charge { get; set; }
        public string Offense_Literal_Identifier_CD { get; set; }
        public string Offense_Degree { get; set; }
        public string BCS_Hierarchy_CD { get; set; }
        public string Offense_Enacted { get; set; }
        public string Offense_Repealed { get; set; }
        public string ALPS_Cognizant_CD { get; set; }
        public string Add_Date_Time { get; set; }
    }
}
