//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIPASTOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schools
    {
        public string CDS_Code { get; set; }
        public string Status { get; set; }
        public string County { get; set; }
        public string District { get; set; }
        public string schoolname { get; set; }
        public string sc_MailCity { get; set; }
        public string sc_DOCType { get; set; }
        public string Schooltype { get; set; }
        public string sc_Latitude { get; set; }
        public string sc_Longitude { get; set; }
    }
}
