//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIPASTOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusMessage_JSON_vw
    {
        public long nid { get; set; }
        public int StopID { get; set; }
        public string StopStatus { get; set; }
        public string code { get; set; }
        public string msg { get; set; }
        public Nullable<int> submissionID { get; set; }
        public Nullable<bool> edited { get; set; }
    }
}
