//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIPASTOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopChangeAudits
    {
        public int ID { get; set; }
        public string OrigJsonStop { get; set; }
        public string ModJsonStop { get; set; }
        public string Reason { get; set; }
        public string NTUserName { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public int StopID { get; set; }
    }
}
